---
- hosts: prod-server
  become: true
  tasks:
  - name: apt update
    apt:
      update_cache: yes

  - name: install docker
    apt:
      pkg: docker.io
      state: present

  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true


  - name: deploy insure-me app
    command: docker run -itd -p 8081:8081 shubhamkushwah123/insure-me:1.0
